routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PrincipalController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [PrincipalController::class, 'principalBaterias'])->name('/');

Route::get('/teoria', [PrincipalController::class, 'teoria'])->name('teoria');

Route::get('/procedimento', [PrincipalController::class, 'procedimento'])->name('procedimento');

Route::get('/medicoes', [PrincipalController::class, 'medicoes'])->name('medicoes');

Route::get('/conclusoes', [PrincipalController::class, 'conclusoes'])->name('conclusoes');

Route::get('/principal', [PrincipalController::class, 'principal']);

Route::get('/pagina1', [PrincipalController::class, 'pagina1']);

Route::get('/pagina2', [PrincipalController::class, 'pagina2']);

app/Models/Medicoes.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Medicoes extends Model
{
    use HasFactory;

    public function getResistenciaInternaAttribute()
    {
        return $this->resistencia_carga * ($this->tensao_sem_carga / $this->tensao_com_carga - 1);
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/PrincipalController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Medicoes;

class PrincipalController extends Controller {

    public function principalBaterias(){
        return view('principalBaterias');
    }

    public function teoria(){
        return view('teoria');
    }

    public function procedimento(){
        return view('procedimento');
    }

    public function medicoes(){
        $medicoes = Medicoes::all();
        return view('medicoes', compact('medicoes'));
    }

    public function conclusoes(){
        return view('conclusoes');
    }

    public function principal(){
        return view('principal');
    }

    public function pagina1() {
        return view('pagina1');
    }

    public function pagina2() {
        return view('pagina2');
    }

}

resources/views/conclusoes.blade.php
@extends('templates.base')

@section('conteudo')
<main>
    <h1>Conclusões</h1>
    <hr>
    <p>
        Após a realização dessa prática concluímos que .......
    </p>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc lacus elit, condimentum at gravida eu, elementum in massa. Fusce at dapibus sem. Donec in hendrerit metus, vitae rutrum nulla. Nulla maximus, nibh vitae vulputate dignissim, purus libero euismod orci, non placerat lorem orci nec massa. Sed at quam eu mi maximus auctor. Etiam tincidunt massa enim, et fermentum nisl vulputate efficitur. Maecenas tristique diam eget maximus congue.
    </p>


    <p>
        Etiam efficitur malesuada nulla ut rutrum. Aliquam pharetra eget augue at rhoncus. In purus diam, fringilla in enim mattis, ornare vestibulum risus. Donec condimentum finibus purus non aliquam. Curabitur sodales odio id magna venenatis, vel tristique justo congue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut quis magna ipsum. Vivamus pharetra sollicitudin maximus. Nullam congue risus leo, consectetur sollicitudin justo laoreet ut. Praesent congue feugiat turpis id efficitur. Quisque sed urna tincidunt mi auctor cursus. Morbi tincidunt rutrum ultricies. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam erat volutpat. Fusce fringilla mollis arcu, nec commodo erat pharetra ac.
    </p>
</main>
@endsection

@section('rodape')
    <h4>Rodapé Conclusões</h4>
@endsection

resources/views/medicoes.blade.php
@extends('templates.base')

@section('conteudo')
<main>
    <h1>Medições</h1>
    <hr>
    <h2>Valores obtidos:</h2>
    <table class="table table-striped table-bordered" id="tbDados">
        <thead>
            <tr>
                <th>Pilha/Bateria</th>
                <th>Tensão nominal (V)</th>
                <th>Capacidade de corrente (mA.h)</th>
                <th>Tensão sem carga(V)</th>
                <th>Tensão com carga(V)</th>
                <th>Resitência de carga(ohm)</th>
                <th>Resistência interna(ohm)</th>
            </tr>
        </thead>
        <tbody>
            @foreach($medicoes as $medicao)
            <tr>
                <td>{{$medicao->pilha_bateria}}</td>
                <td>{{number_format($medicao->tensao_nominal,1,'.','')}}</td>
                <td>{{$medicao->capacidade_corrente}}</td>
                <td>{{$medicao->tensao_sem_carga}}</td>
                <td>{{$medicao->tensao_com_carga}}</td>
                <td>{{$medicao->resistencia_carga}}</td>
                <td>{{number_format($medicao->resistencia_interna,3,'.','')}}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
</main>
@endsection

@section('rodape')
<h4>Rodapé Medições</h4>
@endsection

resources/views/pagina1.blade.php
@extends('templates.base')

@section('conteudo')
    <h2>Página 1</h2>
    <hr>
@endsection

@section('rodape')
    <h4>Rodapé da página 1</h4>
@endsection

resources/views/pagina2.blade.php
@extends('templates.base')

@section('conteudo')
    <h2>Página 2</h2>
    <hr>
@endsection

@section('rodape')
    <h4>Rodapé da página 2</h4>
@endsection

resources/views/principal.blade.php
@extends('templates.base')

@section('conteudo')
    <h2>Página Principal</h2>
    <hr>
@endsection

@section('rodape')
    <h4>Rodapé da página principal</h4>
@endsection

resources/views/principalBaterias.blade.php
@extends('templates.base')

@section('conteudo')
<main>
  <h1>Turma: 2D2 - Grupo 1</h1>
  <h2>Participantes:</h2>
  <hr />

  <table class="table table-striped table-bordered">
    <tr>
      <th>Matrícula</th>
      <th>Nome</th>
      <th>Função</th>
    </tr>
    <tr>
      <td>123456</td>
      <td>José da Silva</td>
      <td>Gerente</td>
    </tr>
    <tr>
      <td>123457</td>
      <td>Maria da Silva</td>
      <td>Desenvolvedor HTML e CSS</td>
    </tr>
    <tr>
      <td>123458</td>
      <td>João da Silva</td>
      <td>Medições e deselvolvedor javascript</td>
    </tr>
  </table>
  <img class="grupo" src="imgs/estudantes.jpeg" alt="Componentes do grupo" />
</main>

@endsection

@section('rodape')
  <h4>Rodapé da página principal</h4>
@endsection

resources/views/procedimento.blade.php
@extends('templates.base')

@section('conteudo')
<main>
    <h1>Procedimentos</h1>
    <hr>
    <h2>Medições:</h2>
    <p>
        Para efetuarmos as medições .......
    </p>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc lacus elit, condimentum at gravida eu, elementum in massa. Fusce at dapibus sem. Donec in hendrerit metus, vitae rutrum nulla. Nulla maximus, nibh vitae vulputate dignissim, purus libero euismod orci, non placerat lorem orci nec massa. Sed at quam eu mi maximus auctor. Etiam tincidunt massa enim, et fermentum nisl vulputate efficitur. Maecenas tristique diam eget maximus congue.
    </p>

    <img class="bateria" src="../imgs/multimetro.webp" alt="multimetro">

    <p>
        Etiam efficitur malesuada nulla ut rutrum. Aliquam pharetra eget augue at rhoncus. In purus diam, fringilla in enim mattis, ornare vestibulum risus. Donec condimentum finibus purus non aliquam. Curabitur sodales odio id magna venenatis, vel tristique justo congue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut quis magna ipsum. Vivamus pharetra sollicitudin maximus. Nullam congue risus leo, consectetur sollicitudin justo laoreet ut. Praesent congue feugiat turpis id efficitur. Quisque sed urna tincidunt mi auctor cursus. Morbi tincidunt rutrum ultricies. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam erat volutpat. Fusce fringilla mollis arcu, nec commodo erat pharetra ac.
    </p>
</main>
@endsection

@section('rodape')
<h4>Rodapé Procedimento</h4>
@endsection

resources/views/templates/base.blade.php
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bateriasaravel</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ asset('css/estilos.css') }}">
</head>

<body>
    <div class="container-md">
        <h1>Baterias Laravel</h1>
        <hr>
        <nav>
            <ul>
                <li><a href="{{ route('/') }}">Início</a></li>
                <li><a href="{{ route('teoria') }}">Teoria</a></li>
                <li><a href="{{ route('procedimento') }}">Procedimento</a></li>
                <li><a href="{{ route('medicoes') }}">Medições</a></li>
                <li><a href="{{ route('conclusoes') }}">Conclusões</a></li>
            </ul>
        </nav>

        @yield("conteudo")
        <div class="rodape container-md">
            @yield("rodape")
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>

</html>

resources/views/teoria.blade.php
@extends('templates.base')

@section('conteudo')
    <main>
        <h1>Teoria</h1>
        <hr>
        <h2>Descrição das pilhas:</h2>
        <p>
            As pilha são constituídas de .......
        </p>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc lacus elit, condimentum at gravida eu, elementum in massa. Fusce at dapibus sem. Donec in hendrerit metus, vitae rutrum nulla. Nulla maximus, nibh vitae vulputate dignissim, purus libero euismod orci, non placerat lorem orci nec massa. Sed at quam eu mi maximus auctor. Etiam tincidunt massa enim, et fermentum nisl vulputate efficitur. Maecenas tristique diam eget maximus congue.
        </p>

        <img class="bateria" src="../imgs/bateria9V.jpeg" alt="bateria">

        <p>
            Etiam efficitur malesuada nulla ut rutrum. Aliquam pharetra eget augue at rhoncus. In purus diam, fringilla in enim mattis, ornare vestibulum risus. Donec condimentum finibus purus non aliquam. Curabitur sodales odio id magna venenatis, vel tristique justo congue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut quis magna ipsum. Vivamus pharetra sollicitudin maximus. Nullam congue risus leo, consectetur sollicitudin justo laoreet ut. Praesent congue feugiat turpis id efficitur. Quisque sed urna tincidunt mi auctor cursus. Morbi tincidunt rutrum ultricies. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam erat volutpat. Fusce fringilla mollis arcu, nec commodo erat pharetra ac.
        </p>
    </main>
@endsection

@section('rodape')
    <h4>Rodapé Teoria</h4>
@endsection